= Besprechungsprotokoll 20.07.2021
Sandy Tang
1.0, 12.03.2020: Some notes
ifndef::imagesdir[:imagesdir: images]
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
//:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]


.Teilnehmer
|===
|anwesend |Verteiler

|Nachname Vorname
|
|TK
|
|TS
|
|MR
|
|ST
|

|===

.Ort und Zeit
[cols=2*]
|===
|Ort
|Online (Discord)

|von-bis
|19:00 - 21:00
|Dauer
|2h
|===


== Besprochene Themen
* Wir haben uns mit unserer Systemarchitektur und unserem Klassendiagramm beschäftigt.
* Weiteres haben wir noch Fragen ausarbeitet bezüglich des Zugriffs vom User auf Musikstücke sowie Videos.
* Ein späterer Schritt wird sein das die Tanzschulbetreiber die Nutzdaten ihrer Videos und Audios einsehen können(Wer spielt wann welche Files ab?).


== Nächste Schritte
* Überarbeitung der Entitys, Repositorys, Tests (kleineres Datenmodel ausarbeiten)
* Youtrack einrichten
* Minimales Frontend(Level auswählen -> Kurs auswählen -> Musik und Video)
* Gliederung schriftlicher Ausarbeitung in Latex



