= Besprechungsprotokoll 28.04.2021
Sandy Tang
1.0, 12.03.2020: Some notes
ifndef::imagesdir[:imagesdir: images]
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
//:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]


.Teilnehmer
|===
|anwesend |Verteiler

|Vorname Nachname
|
|TK
|
|TS
|
|MR
|


|===

.Ort und Zeit
[cols=2*]
|===
|Ort
|Online (Discord)

|von-bis
|20:10 - 21:40
|Dauer
|1h 30min
|===


== Besprochene Themen
* Wir haben in der Diplomarbeitsdatenbank unsere Themenstellung angelegt, welche beinhaltet Ausgangslage, Untersuchungsanliegen individuellen Themenstellungen, Zielsetzun und geplantes Ergebnis.
* Anschließend haben wir Meilensteine für unsere Diplomarbeit festgelegt, sowie auch die Aufteilung unserer individuellen Themenstellungen.
* Weiteres haben wir noch begonnen die rechtlichen Fragen bezüglich unsere Diplomarbeit abzuklären.

== Nächste Schritte
* Eine virtuelle Maschine von Herrn Himmelbauer beantragen.
* Sich mit YouTrack auseinandersetzen, da wir unsere Projektorganisation hiermit regeln werden.
* Ersten Angular Prototype erstellen um Videos und Musikstücke der Tanzschule anzuzeigen.






